wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,22 +2,37 @@ name: CI
 on:
   push:
     branches:
-      - '**'
-      - '!dependabot/**'
+      - 'main'
   pull_request_target:
-    # NOTE: does not work for some reasons
-    # branches:
-    #   - 'dependabot/**'
 
 env:
   ORG_SECRET: ${{ secrets.ORG_SECRET }}
 
 jobs:
-  use_secrets:
+  require-contributor:
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'check if the sender is one of the contributors'
+        run: |
+          list=<<EOL
+            hibariya
+          EOL
+
+          if [[ $list =~ "${{ github.event.sender }}" ]]; then
+            echo "can proceed"
+            exit
+          else
+            echo "cannot proceed"
+            exit 1
+          fi
+
+  use-secrets:
+    needs: ['require-contributor']
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
+          ref: ${{ github.event.pull_request.head.sha }}
           fetch-depth: 0
 
       - name: 'Use secrets'
